### ISSUE TITLE
kubernetes deployment yaml fails because of the container start command in the Pod.

### ISSUE THREAD

**Issue by anmobor2** [grafana/pyroscope#1930]
Setting the image of pyroscope/pyroscope:latest inside my deployment.yaml, the pod didn't start, so I used a kubectl describe pod mypod and I got: 

"failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: “server”: executable file not found in $PATH: unknown"

The I went into the container in the Pod using, tty: true, stdin: true, command: ["sh"], inside the deployment, then in the cli kubectl attach -it pyroscope-647857854-hwsr6 -c pyroscope to look for the executable pyroscope, after that I put the path to "/usr/bin/pyroscope" in my command section in my deployment, together with "sever" and "-no-self-profiling" and it started well.

**Comment by eh-am** [comment]
After some more discussion in the public slack, it seems the problem was a misconfiguration: it was using `command` as opposed to `args`, which is a common mistake. For more info see the following [Stack Overflow question](https://stackoverflow.com/a/66078726).

For documentation purposes, here's a simple `deployment.yaml` example:

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pyroscope
  labels:
    app: pyroscope
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pyroscope
  template:
    metadata:
      labels:
        app: pyroscope
    spec:
      containers:
      - name: pyroscope
        image: pyroscope/pyroscope:latest
        ports:
        - containerPort: 4040
        env:
        - name: PYROSCOPE_LOG_LEVEL
          value: "debug"
        args:
        - "server"
        - "-no-self-profiling"
```
