### ISSUE TITLE
Figure how to run the store-gateway when using single-binary

### ISSUE THREAD

**Issue by cyriltovena** [grafana/pyroscope#2045]
Right now the store gateway is not enable when using single binary, but we should definitively have it if you run using an cloud object storage.

**Comment by simonswine** [comment]
Just to add a bit more context: For different components we use the [dskit/modules](https://pkg.go.dev/github.com/grafana/dskit@v0.0.0-20230808012443-3f5683fdb201/modules) package, you can find the original[ design for Cortex ](https://cortexmetrics.io/docs/proposals/generalize-modules/)(proper ancient).

The role of the store-gateway is very similar how it is explained in Grafana Mimir https://grafana.com/docs/mimir/latest/references/architecture/components/store-gateway/

**Comment by hi-rustin** [comment]
I am working on this.

**Comment by hi-rustin** [comment]
Oh, I guess the failure was caused by my env.

After I changed the config to:
```yaml
# Do not use this configuration in production.
# It is for demonstration purposes only.
scrape_configs:
  - job_name: "default"
    scrape_interval: "15s"
    static_configs:
      - targets: ["127.0.0.1:4100"]
        labels:
          service_name: "service-demo"

# storage:
#   backend: s3
#   s3:
#     endpoint: 127.0.0.1:9000
#     bucket_name: test
#     insecure: true
#     access_key_id: minioadmin
#     secret_access_key: minioadmin


storage:
  backend: filesystem
  filesystem:
    dir: /tmp/pyroscope

```

Then it worked well.
