### ISSUE TITLE
Ensure presence of `service_name` label in grafana agent

### ISSUE THREAD

**Issue by Rperry2174** [grafana/pyroscope#2055]
In https://github.com/grafana/phlare/pull/710 we changed `pyroscope_app` to service name. The reasoning for this is so that we can create UX centered around the certainty that there is at least one label which we can be sure exists. This is possible because in all of these SDKs there exists a concept of `application_name` which is converted to `service_name` when sent to phlare. 

This works automatically for all profiles that are sent in push mode from language SDK. For Grafana Agent which uses pull mode (currently only for Go), there is no guarantee that there will be a `service_name` set by a user, but we would like to make sure one exists for consistency. 

Some options:
### Option A: Make user set this explicitly i.e. [og-pyroscope pull mode scrape configuration](https://pyroscope.io/docs/golang-pull-mode/#scrape-configuration)
```
---
# A list of scrape configurations.
scrape-configs:
  # The job name assigned to scraped profiles by default.
  - job-name: pyroscope

    # How frequently to scrape targets by default.
    scrape-interval: 10s

    # The list of profiles to be scraped from the targets.
    enabled-profiles: [cpu, mem, goroutines, mutex, block]

    # List of labeled statically configured targets for this job.
    static-configs:
      - application: my-application-name
        spy-name: gospy
        targets:
          - hostname:6060
        labels:
          env: dev
```

### Option B: Infer `service_name` from scraped data
```
/Users/placeholder/work/phlare/pkg/querier/querier_test.go:1002: Mapping (10): /usr/local/bin/kustomize-controller  Locations: 13786 percentage:7.76
    /Users/placeholder/work/phlare/pkg/querier/querier_test.go:1002: Mapping (11): /usr/bin/phlare  Locations: 16179 percentage:9.11
    /Users/placeholder/work/phlare/pkg/querier/querier_test.go:1002: Mapping (12): /usr/bin/metrics-recommendations  Locations: 2625 percentage:1.48
    /Users/placeholder/work/phlare/pkg/querier/querier_test.go:1002: Mapping (13): /bin/drone-server  Locations: 1911 percentage:1.08
    /Users/placeholder/work/phlare/pkg/querier/querier_test.go:1002: Mapping (14): /app/grafana-drone-extension  Locations: 710 percentage:0.40

```
In this case `kustomize-controller`, `phlare`, `metrics-recommendations`, etc can be used for `service_name`

### Option C: Infer `service_name`, but allow for overrides
The third option simply infers  the service name if none is explicitly set and overrides it if it is.
I suspect this will be the best option moving forward

Note: there is an example of grafana agent [here](https://github.com/grafana/pyroscope/pull/1958)
