### ISSUE TITLE
Helm ingress doesn't support pyroscope ingress

### ISSUE THREAD

**Issue by simonswine** [grafana/pyroscope#2062]

**Comment by macmiranda** [comment]
Hi @simonswine, do you mean that the Ingress object created by Helm will not support the Pyroscope UI?

I haven't tried it myself but looking at the templates, it does seem like it. I have created an Ingress manually with Prefix `/` and it works fine.

Is that what you have in mind?

**Comment by rlex** [comment]
Ingress seemingly only supports certain paths, but not web ui.

Fix is simple, just add 

```
          - path: /
            pathType: Prefix
            backend:
              service:
                name: pyroscope
                port:
                  number: 4040
```

to list of paths under ingress somewhere here: https://github.com/grafana/pyroscope/blob/main/operations/pyroscope/helm/pyroscope/templates/ingress.yaml#L25
