### ISSUE TITLE
[helm] add gateway similar to tempo/loki

### ISSUE THREAD

**Issue by rlex** [grafana/pyroscope#2082]
#### Is your feature request related to a problem? Please describe.

Will be good if we can add gateway for ingress like in tempo/loki charts with http auth. Maybe port it directly from that charts?

**Comment by dd84ai** [comment]
if you are using Ingress Nginx, there is elegant workaround for having basic auth at least by using its annotations which we can input in helm chart
```yaml
ingress:
  enabled: true
  className: nginx
  annotations:
    # type of authentication
    nginx.ingress.kubernetes.io/auth-type: basic
    # name of the secret that contains the user/password definitions
    nginx.ingress.kubernetes.io/auth-secret: basic-auth
    # message to display with an appropriate context why the authentication is required
    nginx.ingress.kubernetes.io/auth-realm: 'Authentication Required - foo'
    cert-manager.io/cluster-issuer : "letsencrypt"
  hosts:
    - "pyroscope.${zone}"
  tls:
    - secretName: "pyroscope-ssl"
      hosts:
        - "pyroscope.${zone}"
```
official guide
https://kubernetes.github.io/ingress-nginx/examples/auth/basic/

password verification
https://stackoverflow.com/questions/24147067/verify-user-and-password-against-a-file-created-by-htpasswd
