### ISSUE TITLE
Add support for standard AWS authentication in s3 backend.

### ISSUE THREAD

**Issue by petethepig** [grafana/pyroscope#2339]
Currently we require users to provide AWS credentials in plain text. However, AWS supports many other authentication methods.

All of AWS tools and sdks support all of those auth methods natively and so AWS users are very familiar with them and often expect them to work in other products. 

We use Thanos S3 configuration bits an pieces. Thanos also supports a mode where authentication settings are picked up from user's environment (e.g ~/.aws/credentials, instances metadata, session profiles, etc). The parameters is called [`aws_sdk_auth`](https://github.com/thanos-io/objstore#:~:text=However%20if%20you%20set%20aws_sdk_auth%3A%20true)  We could probably adopt whatever Thanos is doing pretty easily.

There's [Slack thread](https://pyroscope.slack.com/archives/C01FJRYENPQ/p1693347838548019) where a community member is asking about this functionality.

**Comment by caiobegotti** [comment]
Thanks for creating the issue! It's SO but the question and answers are pretty straightforward as a reference on how this works with Thanos and Tempo today using IRSA (service accounts annotated to be used by Pyroscope pods with the appropriate IAM and roles): https://stackoverflow.com/questions/64016099/thanos-s3-config

**Comment by luisgerhorst** [comment]
I'm not sure if this is intentional, but by setting Pyroscope config's `storage.s3.access_key_id` and `storage.s3.secret_access_key` to the empty string `""`, you can make thanos fall back to retrieving the credentials from the environment (see https://github.com/thanos-io/objstore/blob/eb01c83b89a468b19b04fe913c97c495ddc73fc4/providers/s3/s3.go#L243). I am successfully using this with an authorized Kubernetes service account in AWS to make Pyroscope use S3 as an object storage.

**Comment by caiobegotti** [comment]
But how did you get the service account used by Pyroscope to have such permissions in AWS? IRSA? Mind sharing your configs? It's not entirely clear to me how that would work with the documented configs of 1.0.

**Comment by luisgerhorst** [comment]
Yes, IRSA, here's AWS' guide: https://docs.aws.amazon.com/eks/latest/userguide/iam-roles-for-service-accounts.html

On the Pyroscope side you just have to put the S3 bucket into the config and set the Helm chart's `values['pyroscope']['serviceAccount']['create'] = false` and `values['pyroscope']['serviceAccount']['name'] = serviceAccountName`.

When deploying Pyroscope using AWS CDK and Helm, the relevant part looks as follows:
```
// cluster: eks.Cluster/FargateCluster
// bucket: s3.Bucket
// region: AWS Region (e.g., eu-central-1)
// values: Load YAML from template file

// Create a service account that already has all the setup from
// https://docs.aws.amazon.com/eks/latest/userguide/iam-roles-for-service-accounts.html
// done, except for the "Configuring Pods to use a Kubernetes service
// account" step. We will modify the Helm chart values below to do that.
const serviceAccount = cluster.addServiceAccount("PyroscopeS3", { name: "pyroscope-s3" });
bucket.grantReadWrite(serviceAccount);

values['pyroscope']['structuredConfig']['storage']['s3']['bucket_name'] = bucket.bucketName;
// dualstack because we want IPv6.
values['pyroscope']['structuredConfig']['storage']['s3']['endpoint'] = `s3.dualstack.${region}.amazonaws.com`;
values['pyroscope']['structuredConfig']['storage']['s3']['region'] = region;

// Tell pyroscope to use the serviceAccount we created, which has permissions
// to S3.
values['pyroscope']['serviceAccount']['create'] = false;
values['pyroscope']['serviceAccount']['name'] = serviceAccount.serviceAccountName;

cluster.addHelmChart('PyroscopeChart', {
  values: values,
  // ...
}
```

**Comment by caiobegotti** [comment]
Ah, I see what you mean, and Pyroscope 1.0's chart accepts annotations in SAs so I think that will work, let me test it and report back soon.

**Comment by caiobegotti** [comment]
No luck so far @luisgerhorst so would you mind sharing the storage bits of your `https://<URL>/api/v1/status/config` please?

Here's mine for reference, trying to match what you described before:

```
storage:
    backend: s3
    s3:
        endpoint: s3.amazonaws.com
        region: eu-west-1
        bucket_name: MYBUCKET
        secret_access_key: ""
        access_key_id: ""
        insecure: true
        signature_version: v4
```

Note the 2 empty `""` keys settings, like you said you're using.

With that I just get `ts=2023-09-04T19:01:10.356894643Z caller=instance.go:95 level=error tenant=anonymous msg="shipper run failed" err="upload 01H9GMTJZ9K9AS00GXX9Z5FQPW: uploading file 'index.tsdb': upload file data/anonymous/local/01H9GMTJZ9K9AS00GXX9Z5FQPW/index.tsdb as 01H9GMTJZ9K9AS00GXX9Z5FQPW/index.tsdb: upload s3 object: Access Denied"` from Pyroscope, nothing else. Even when setting log level to debug by the way @petethepig 

My IRSA role has these to basically do whatever it needs to the S3 bucket:
```
            "Action": "s3:*",
            "Effect": "Allow",
```

Pyroscope's pod is using the service account `serviceAccountName: pyroscope` pointing to that same IRSA role via the AWS annotation, as such:

```
apiVersion: v1
kind: ServiceAccount
metadata:
  name: pyroscope
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::MYACCOUNT:role/pyroscope-role
```

That's exactly what I do with Tempo and Thanos already, so I'm curious about your `api/v1/status/config` output 🙏

**Comment by luisgerhorst** [comment]
Here you go:

```
storage:
    backend: s3
    s3:
        endpoint: s3.dualstack.$region.amazonaws.com
        region: $region
        bucket_name: $bucketname
        secret_access_key: ""
        access_key_id: ""
        insecure: false
        signature_version: v4
        sse:
            ...
        http:
            idle_conn_timeout: 1m30s
            response_header_timeout: 2m0s
            insecure_skip_verify: false
            tls_handshake_timeout: 10s
            expect_continue_timeout: 1s
            max_idle_connections: 100
            max_idle_connections_per_host: 100
            max_connections_per_host: 0
```

Why would you pass `insecure: true` and not use regional S3 endpoints? Also, I am not sure if your role policy and ServiceAccount config are equivalent to what CDK generates.

**Comment by caiobegotti** [comment]
Thank you dude! Yeah, insecure didn't feel right but it was the default config from Pyroscope and I'll need to force it to false. Your HTTP settings are quite useful by the way, much appreciated. I'll report back time soon again 👌

**Comment by caiobegotti** [comment]
Hmm ok, so... it's working now ✌️ but the only thing I did change comparing what we discussed before is that `endpoint: s3.eu-west-1.amazonaws.com` has the region in it. Uh? I'm not using dualstack because I don't need it.

My Thanos storage uses `endpoint: s3.amazonaws.com` just fine without region and I understood Pyroscope was using the same code by Thanos storage's settings. Am I crazy here about needing the region and to make it work?

Regarding IRSA, I'm gonna share what I have exactly for the people living in the future trying to google it...

Role policy:
```
{
	"Statement": [
		{
			"Action": "s3:ListBucket",
			"Effect": "Allow",
			"Resource": "arn:aws:s3:::BUCKETNAME"
		},
		{
			"Action": [
				"s3:PutObjectTagging",
				"s3:PutObject",
				"s3:ListBucket",
				"s3:GetObjectTagging",
				"s3:GetObject",
				"s3:DeleteObject"
			],
			"Effect": "Allow",
			"Resource": "arn:aws:s3:::BUCKETNAME/*"
		}
	],
	"Version": "2012-10-17"
}```

Pyroscope chart values:
```
pyroscope:
  minio:
    enabled: false
  pyroscope:
    persistence:
      enabled: false
    structuredConfig:
      storage:
        backend: s3
        s3:
          insecure: false
          endpoint: s3.eu-west-1.amazonaws.com
          bucket_name: BUCKETNAME
          region: eu-west-1
          access_key_id: ''
          secret_access_key: ''
    serviceAccount:
      annotations:
        eks.amazonaws.com/role-arn: "arn:aws:iam::YOURACCOUNT:role/YOURROLE"
```

Perhaps it would be interesting to have in the Pyroscope docs something like https://grafana.com/docs/tempo/latest/configuration/s3/#amazon-s3-permissions too. It's essentially the above settings but I suppose @petethepig some error handling or more debug messages would be cool around that piece of code. I mean not requiring the AWS keys options at all and then when they're missing just print a message saying to use IRSA.

**Comment by Krithika3** [comment]
@caiobegotti how are you passing this config to your K8s server?

**Comment by Krithika3** [comment]
@caiobegotti Sorry for the vagueness, let me clarify. I was talking about the {code} structuredConfig:
      storage:
        backend: s3
        s3:
          insecure: false
          endpoint: s3.eu-west-1.amazonaws.com
          bucket_name: BUCKETNAME
          region: eu-west-1
          access_key_id: ''
          secret_access_key: ''
    serviceAccount:
      annotations:
        eks.amazonaws.com/role-arn: "arn:aws:iam::YOURACCOUNT:role/YOURROLE"{code} How did you pass this config through? I am assuming through config maps :) But it would not take in service account in the config map so I was curious.

**Comment by caiobegotti** [comment]
That's the part you add to your Helm chart's values.yaml when installing Pyroscope via Helm with `helm instal ... -f values.yaml` as usual.

**Comment by slobad123** [comment]
I am on an ec2 instance with a configured IAM instance profile granting full access to an s3 bucket and its contents. I am able to access the s3 bucket using the aws cli, but when I try to access it through Pyroscope, I get "Access Denied" errors in the logs.

Looking at the CloudTrail logs, it is being denied because my user identity is set to "anonymous":

```
    "userIdentity": {
        "type": "AWSAccount",
        "principalId": "",
        "accountId": "anonymous"
    },
```

The workaround of specifying empty string for access key and access doesn't seem to work for me. This is the s3 config I'm using:

```
storage:
  backend: s3
  s3:
    bucket_name: my-bucket-name
    region: us-west-2
    endpoint: s3.us-west-2.amazonaws.com
    secret_access_key: ''
    access_key_id: ''
    sse:
      type: SSE-S3
    http:
      idle_conn_timeout: 1m30s
      response_header_timeout: 2m0s
      insecure_skip_verify: false
      tls_handshake_timeout: 10s
      expect_continue_timeout: 1s
      max_idle_connections: 100
      max_idle_connections_per_host: 100
      max_connections_per_host: 0
```

I looked into the Thanos code a bit:
https://github.com/thanos-io/objstore/blob/19b0c0f0ffd88f0ba8266a8ef6cbec7135bd2e15/providers/s3/s3.go

```
	if config.AWSSDKAuth {
		chain = []credentials.Provider{
			wrapCredentialsProvider(&AWSSDKAuth{Region: config.Region}),
		}
	} else if config.AccessKey != "" {
		chain = []credentials.Provider{wrapCredentialsProvider(&credentials.Static{
			Value: credentials.Value{
				AccessKeyID:     config.AccessKey,
				SecretAccessKey: config.SecretKey,
				SessionToken:    config.SessionToken,
				SignerType:      credentials.SignatureV4,
			},
		})}
	} else {
		chain = []credentials.Provider{
			wrapCredentialsProvider(&credentials.EnvAWS{}),
			wrapCredentialsProvider(&credentials.FileAWSCredentials{}),
			wrapCredentialsProvider(&credentials.IAM{
				Client: &http.Client{
					Transport: http.DefaultTransport,
				},
				Endpoint: config.STSEndpoint,
			}),
		}
	}
```

I expect I'm falling into the else block here because config.AWSSDKAuth is not settable from Pyroscope and AccessKey is empty string. I'm not setting any environment variables and do not have an `.aws` directory with credentials, so I suspect it is trying the MinIO `credentials.IAM` provider but it is failing for whatever reason.

Is this expected to work?

Loki and Mimir are configured on the same ec2 instance and both are able to rely on the IAM instance profile to gain access to s3 (no access key/secret configured for them)

It would be nice if the AWS SDK Auth were supported. Thanks
