### ISSUE TITLE
Naming of datasource in Grafana

### ISSUE THREAD

**Issue by petethepig** [grafana/pyroscope#2349]
There’s a bit of an issue with our datasource configuration in Grafana. The correct config for the v1.0.0 datasource is actually this:
```
---
datasources:
  - name: Pyroscope
    type: 'phlare'
    url: http://pyroscope:4040
    jsonData:
      backendType: 'phlare'
```

^ note how both `type` and `backendType` are set to `phlare`. It doesn't work if I set `type` to `pyroscope`. If I set `backendType` to `pyroscope`, that actually makes it work with OG pyroscope.

This leads to confusion among users, e.g [look at this conversation in slack](https://pyroscope.slack.com/archives/C01FJRYENPQ/p1693440546441119) (visit [pyroscope.io/slack](https://pyroscope.io/slack) to join that slack).

---

We need to fix both of these. We discussed the first one (`type`) in the past, although I couldn't find an issue (@aocenas — feel free to add it here if there is one). If I remember correctly, the fix is not straightforward, but at least it's possible.

The `backendType` is trickier because if you set `backendType` to `pyroscope` that actually already means something (`og pyroscope`) and so that makes everything more confusing and complex. Best solution I can come up with right now is to not advertise `backendType` setting in our docs at all and let Grafana self-select the right type.

---

cc @aocenas @Rperry2174 — curious what you guys think

**Comment by aocenas** [comment]
So the type of the data source now is `grafana-pyroscope-datasource` (the naming is a bit awkward but that is the naming convention now). `phlare` still works as an alias for backward compatibility. I see that we have the `phlare` type in the [docs](https://grafana.com/docs/grafana/latest/datasources/grafana-pyroscope/) though so this should be changed.

Regarding the `backendType`, yeah not sure how to proceed with that. My thought originally was that we would either have 3rd option later for new pyroscope or we would just still have api compatible with og pyroscope so `pyroscope` would be a default option. It seems though that we actually have kept the `phlare` api which means that now for the new backend we need backendType `phlare` which yeah is confusing.

For context about the auto detection of the backendType. We have that but when user configures the data source through UI. Having the manual switch is there mainly as a fallback if something goes wrong or for some testing etc. This means though that it does not kick in for provisioning. I guess ideally we would just have an `auto` option (when backendType is not set) and we would detect the backend every time it's needed. I will have to check how to do this as we use different clients on the backend and so we would have to do it for every request (which may be a bit costly) so we would ideally still preserve the value at least for an user session or something like that. An easier solution would still be to just introduce a 3rd option `grafana pyroscope` or something like that.

**Comment by cyriltovena** [comment]
So this doesn't work
```
datasources:
  pyroscope.yaml:
   apiVersion: 1
   datasources:
   - name: Pyroscope
     type: pyroscope
     uid: pyroscope-test
     url: http://pyroscope-querier.pyroscope-test.svc.cluster.local.:4040/
```

Because that's what we have in the doc ?
