### ISSUE TITLE
RAM usage only going up

### ISSUE THREAD

**Issue by ythomop** [grafana/pyroscope#2456]
I have setup a pyroscope service in a relatively simple docker environment. The pyroscope config is the following:
```
limits:
  max_profile_size_bytes: 0
  max_profile_stacktrace_samples: 0
  ingestion_rate_mb: 20
  ingestion_burst_size_mb: 20
```

The reasoning behind the config is that the app I want to profile sends large profiles, relatively to the default limits, but I don't know why. 
However, I don't think that the expected behaviour of pyroscope is this memory graph:
![image](https://github.com/grafana/pyroscope/assets/35526357/f5f661c4-2237-465a-a9be-41c718e13c81)

I was looking for in-memory retention configuration options but I didn't find anything.

Is this expected? If yes, what can one do to not have the profiling server run OOM eventually? (already happened once)

**Comment by kolesnikovae** [comment]
Hello @ythomop, thank you for reporting the issue.

Could you please specify the version you're using? Do you have self-profiling enabled? Being able to check the memory in-use profile of the pyroscope server itself would make the investigation much easier.

> The reasoning behind the config is that the app I want to profile sends large profiles, relatively to the default limits, but I don't know why.

Which SDKs you are using?

**Comment by ythomop** [comment]
> Could you please specify the version of the pyroscope server? 

v1.0.0 from the latest docker tag

> Do you have self-profiling enabled? Being able to check the memory in-use profile of the pyroscope server itself would make the investigation much easier.

You're right, I forgot that. 
- [inuse_space](https://flamegraph.com/share/6476b469-5d01-11ee-b10e-723ba4706d7b) 
- [inuse_objects](https://flamegraph.com/share/4c50c95f-5d01-11ee-b135-0a855ce7b751)

Let me know if you need any other profiles.

> Which SDKs are you using?

I'm not sure if that's what you're asking, but the profiles are served using golang's `net/http/pprof` package.
```go
r.Handle("/debug/pprof/goroutine", pprof.Handler("goroutine"))
r.Handle("/debug/pprof/heap", pprof.Handler("heap"))
```

**Comment by ythomop** [comment]
> Maybe we should take a look at the diff of profiles with a 3 hours difference (the default block duration)? 

[inuse_space_07:44-08:44](https://flamegraph.com/share/65fb09c8-5d12-11ee-b10e-723ba4706d7b)
[inuse_space_10:44-11:44](https://flamegraph.com/share/7840db14-5d12-11ee-b10e-723ba4706d7b)
[inuse_objects_07:44-08:44](https://flamegraph.com/share/53f1679a-5d12-11ee-b135-0a855ce7b751)
[inuse_objects_10:44-11:44](https://flamegraph.com/share/3cfd22d2-5d12-11ee-b10e-723ba4706d7b)

(local time)

> Could you also please clarify which exactly metric is shown in the screenshot (RSS, VSZ, etc) 

The metric shown is cAdvisor's `container_memory_usage_bytes`, which according to [this](https://github.com/google/cadvisor/issues/1744#issuecomment-451330944) is `container_memory_usage_bytes == container_memory_rss + container_memory_cache + container_memory_swap + kernel memory`

> and how the server is deployed (k8s, docker, dedicated node)?

It's deployed using docker-compose:
```
  agent:
    image: grafana/agent
    ports:
      - "127.0.0.1:12345:12345"
    volumes:
      - ./grafana/agent/config.river:/etc/agent/config.river
    environment:
      AGENT_MODE: flow
    command: run --server.http.listen-addr=0.0.0.0:12345 /etc/agent/config.river
  pyroscope:
    image: grafana/pyroscope
    ports:
      - "127.0.0.1:4040:4040"
    command: -config.file=/config.yml
    volumes:
      - ./pyroscope.config.yml:/config.yml
      - pyroscope_data:/data
```

Also, this is `grafana agent`'s config, in case it plays any role:
```
logging {
  level  = "info"
  format = "logfmt"
}

pyroscope.write "writer" {
  endpoint {
    url = "http://pyroscope:4040"
  }
}

pyroscope.scrape "default_settings" {
  targets    = [ { "__address__" = "api:8008", "service_name" = "api" } ]
  forward_to = [pyroscope.write.writer.receiver]
  profiling_config {
    profile.goroutine {
      enabled = true
      path = "/debug/pprof/goroutine"
    }
    profile.custom "HEAP" {
        enabled = true
        path = "/debug/pprof/heap"
    }
    profile.process_cpu {
      enabled = true
      path = "/debug/pprof/profile"
    }
  }
}
```
