### ISSUE TITLE
Add support for Azure Workload Identity

### ISSUE THREAD

**Issue by janlonsetteig** [grafana/pyroscope#2680]
We want to deploy Pyroscope on our AKS clusters along side Loki and Tempo. Storage for all will be Azure blob storage containers.

For Loki and Tempo we use Workload Identity so that we do not have to deal with account keys. We would like to do the same thing with Pyroscope so that we have a consistent configuration and deployment across all the Grafana products we use.

This works as follows:
* We have an existing Service Account that have
```yaml
  annotations:
    azure.workload.identity/client-id: xxxxxx
    azure.workload.identity/tenant-id: yyyyyy
  labels:
    azure.workload.identity/use: "true"
```
* In the deployments we disable creation of a service account and configure it to use the one described above
* The application pods gets this label
```yaml
    labels:
      azure.workload.identity/use: "true"
```
* In the application storage configuration for azure we specify these settings. Is is slightly different for Tempo and Loki, but the principle is the same

Loki:
```yaml
    storage:
      type: azure
      azure:
        useFederatedToken: true
        account_name: zzzzz
        container_name: loki
        use_managed_identity: false
```
Tempo:
```yaml
  storage:
    trace:
      backend: azure
      azure:
        use_federated_token: true
        storage_account_name: zzzzz
        container_name: tempo
        use_v2_sdk: true
```

It would be great if we could also use Workload Identity for the Pyroscope Azure storage
