### ISSUE TITLE
Upgrading from 1.0.0 to 1.1.5 changes profiling type with Python SDK

### ISSUE THREAD

**Issue by aurbina83** [grafana/pyroscope#2687]
I'm currently using the Python SDK - version 0.8.5

Without any changes in my implementation on my service, after upgrading to Pyroscope 1.1.5, suddenly my `profile_type` is only `process_cpu:samples` where before it was `process_cpu.cpu`.

This is without changing any configs at all. Simply updating the docker image tag.

For brevity, I'll share my configs. 

It's pretty bare because it's something we use locally to help debug some bottlenecks.

```yaml
# Pyroscope config
server:
  http_listen_port: 4040

limits:
  max_query_length: 5d
  max_query_lookback: 10d

self_profiling:
  disable_push: true
```

```yaml
# grafana data sources
apiVersion: 1

datasources:
- name: Loki
  type: loki
  url: http://loki:3100
  isDefault: true
  editable: true
  jsonData:
    derivedFields:
      - name: "request_tag"
        matcherRegex: '"request_id"\s*:\s*"(\w+)"'
        url: 'process_cpu:cpu:nanoseconds:cpu:nanoseconds{request_tag="$${__value.raw}"}'
        datasourceUid: pyroscope
      - name: "dd_tag"
        matcherRegex: '"dd\.trace_id"\s*:\s*"(\w+)"'
        url: 'process_cpu:cpu:nanoseconds:cpu:nanoseconds{dd_tag="$${__value.raw}"}'
        datasourceUid: pyroscope
- name: Pyroscope
  type: grafana-pyroscope-datasource
  uid: pyroscope
  url: http://pyroscope:4040
  ```

Not sure what changed or if there's some config changes I need to make to get the cpu profile types back.
