### ISSUE TITLE
UI does not function behind reverse proxy

### ISSUE THREAD

**Issue by fsiler** [grafana/pyroscope#3113]
#### Describe the bug
I've toyed with different configurations of api.base-url and server.http_path_prefix.  System will not function when pushed to /pyroscope

#### To Reproduce

1. Start Pyroscope (SHA or version)

1.4.0

2. Perform Operations(Read/Write/Others)

Configure as follows:
```yaml
server:
  http_listen_port: 4040
## FMS: these don't appear to work properly for reverse proxy use in 1.4.0
  http_path_prefix: /pyroscope
api:  
  base-url: /pyroscope
```

#### Expected behavior

Port-forward config, try to visit UI at /pyroscope.  Does not work.  Used both `kubectl port-forward` and `HTTPProxy` frontend, all broken.

Notably, I can visit `/pyroscope/ready` and it functions.  Not sure about other API endpoints.

#### Environment

- Infrastructure: Kubernetes configured with `config.yaml` mapped via ConfigMap
- Deployment tool: Helm

#### Additional Context

n/a

**Comment by hazra-mms** [comment]
I experience the same behaviour adding the base-url config during configuring from the Helm chart. I tried to use port-forward and the UI comes blank.

**Comment by sylr** [comment]
Same here, trying to setup pyroscope behind tailscale serve but it does not work:

```
https://tragicomix.xxxxxxxx.ts.net (tailnet only)
|-- /grafana   proxy http://127.0.0.1:3000
|-- /pyroscope proxy http://127.0.0.1:4000
```

```yaml
---
api:
  base-url: /pyroscope
server:
  http_path_prefix: /pyroscope
pyroscopedb:
  data_path: /opt/homebrew/var/lib/pyroscope
```
