### ISSUE TITLE
Jsonnet dashboards job selectors are not aligned with monitoring resources

### ISSUE THREAD

**Issue by github-vincent-miszczak** [grafana/pyroscope#3223]
#### Describe the bug
Jsonnet dashboards `job` selectors are not aligned with monitoring resources.
`job` selectors in panels use `PodMonitor` [syntax](https://github.com/grafana/pyroscope/blob/main/operations/pyroscope/jsonnet/pyroscope-mixin/pyroscope-mixin/dashboards/pyroscope-reads.libsonnet#L19), while the monitoring is [deployed](https://github.com/grafana/pyroscope/blob/main/operations/pyroscope/helm/pyroscope/templates/servicemonitor.yaml) with `ServiceMonitor`, and the job names are service names.

#### To Reproduce
- deploy Pyroscope using Helm, enabling monitoring (`serviceMonitor.enabled: true`)
- generate dashboards and import them into Grafana

#### Expected behavior

Prometheus requests from the panels should be aligned with metrics from service monitors.

#### Environment

Kubernetes/Helm

**Comment by greenled** [comment]
It is possible to go in the opposite direction instead. I like the `<namespace>/<component>` format, which is already followed by Mimir and Loki. So I relabeled the chart's metrics to match the queries in the Jsonnet mixins:

```yaml
serviceMonitor:
  enabled: true
  relabelings:
    - sourceLabels:
        - __meta_kubernetes_namespace
        - __meta_kubernetes_service_label_app_kubernetes_io_component
      separator: "/"
      targetLabel: job
```
