### ISSUE TITLE
Common variables in docker-compose.yml

### ISSUE THREAD

**Issue by melanmeg** [grafana/pyroscope#3536]
Hello "pyroscope" Team,

As a minor point, I suggest the following modifications.

### Description:
By defining shared environment variables in a single location, we aim to simplify the configuration process and improve maintainability across different services.

_Should I include this fix?_

### Key Changes:
- Added `x-service: &rideshare-go-template` to commonize rideshare-go-eu-north and rideshare-go-ap-south.
- Added `x-environment: &otel` to store common environment variables.

The relevant source code is [docker-compose.yml](https://github.com/grafana/pyroscope/blob/main/examples/tracing/tempo/docker-compose.yml)

As follows.

```yaml
x-service: &rideshare-go-template
  ports:
    - 5000
  environment: &env
    PYROSCOPE_SERVER_ADDRESS: http://pyroscope:4040
    OTLP_URL: tempo:4318
    OTLP_INSECURE: 1
    DEBUG_LOGGER: 1
  build:
    context: ../../language-sdk-instrumentation/golang-push/rideshare

x-environment: &otel
  <<: *env
  OTEL_TRACES_EXPORTER: otlp
  OTEL_EXPORTER_OTLP_ENDPOINT: http://tempo:4317
  OTEL_METRICS_EXPORTER: none
  OTEL_TRACES_SAMPLER: always_on
  OTEL_PROPAGATORS: tracecontext

services:
  rideshare-go-ap-south:
    <<: *rideshare-go-template
    hostname: rideshare-go-ap-south
    environment:
      REGION: ap-south

  rideshare-go-eu-north:
    <<: *rideshare-go-template
    hostname: rideshare-go-eu-north
    environment:
      REGION: eu-north

  rideshare-java-us-east:
    ports:
      - 5000
    hostname: rideshare-java-us-east
    environment:
      <<: *otel
      OTEL_SERVICE_NAME: rideshare.java.push.app
      PYROSCOPE_LABELS: hostname=rideshare-java-us-east
      REGION: us-east
    build:
      context: ../../language-sdk-instrumentation/java/rideshare
      dockerfile: Dockerfile.otel-instrumentation
...
```
