### ISSUE TITLE
Is there server configuration yaml file example ?

### ISSUE THREAD

**Issue by 3AceShowHand** [grafana/pyroscope#3568]
I just need one server configuration yaml file example, which contains the most basic configurations, can be used to start the cluster, the following things should be included:
* how to add scrape instance, profiling contents etc.

Your provided configuration parameter is not easy for new coming user, if they want to deploy a basic cluster to try.

Previous, there is one configuration example provided in the old version, but this one cannot be used anymore. For example:
```
server:                                                                                                                                                            [0/678]
  http_listen_port: 4040

retention: 6h

scrape-configs:
  - job-name: test-cluster
    enabled-profiles: [cpu, mem, goroutines, block, mutex]

    static-configs:
      - application: xxx
        spy-name: gospy
        targets:
          - localhost:2333
        labels:
          env: dev
```
