### ISSUE TITLE
Improve update contributors CI

### ISSUE THREAD

**Issue by aleks-p** [grafana/pyroscope#3574]
#3556 addressed an issue when we need to release a new version and the latest commit to main was made via the "update contributors" CI action. The side effect of the fix is that we now try to push and deploy images twice for each push to main. This results in cancelled jobs and docker image tags pointing to uninteresting commits.

It would be nice if we can skip unnecessary job runs while still having the release pipeline work properly. 

cc @korniltsev @marcsanmi

**Comment by marcsanmi** [comment]
The jobs were canceled due to the concurrency configuration in the CI workflow. 
```
concurrency:
  # Cancel any running workflow for the same branch when new commits are pushed.
  # We group both by ref_name (available when CI is triggered by a push to a branch/tag)
  # and head_ref (available when CI is triggered by a PR).
  group: "${{ github.ref_name }}-${{ github.head_ref }}"
  cancel-in-progress: true
```
This setup cancels any running workflow for the same branch when new commits are pushed. By removing `[skip ci]` from contributor updates, these commits started triggering new workflow runs. Each new run canceled the previous one that was still in progress for the same branch. This led to ongoing jobs, like building and pushing images, being canceled before they could complete.
