### ISSUE TITLE
magic ip: scheduler_processor and frontend_scheduler_worker

### ISSUE THREAD

**Issue by nexcode** [grafana/pyroscope#3617]
compose.yaml:
```
services:
  service:
    image: grafana/pyroscope:1.9.0
    command:
      - --config.file=/etc/pyroscope/pyroscope.yaml
    network_mode: host
    restart: on-failure
    volumes:
      - ./pyroscope.yaml:/etc/pyroscope/pyroscope.yaml:ro
```

pyroscope.yaml:
```
server:
  http_listen_address: 127.0.0.1
  http_listen_port: 3300
  grpc_listen_address: 127.0.0.1
  grpc_listen_port: 9395

frontend:
  address: 127.0.0.1

ingester:
  lifecycler:
    address: 127.0.0.1
    ring:
      kvstore:
        store: inmemory

compactor:
  sharding_ring:
    instance_addr: 127.0.0.1
    kvstore:
      store: inmemory

store_gateway:
  sharding_ring:
    instance_addr: 127.0.0.1
    kvstore:
      store: inmemory

```

errors:
```
ts=2024-10-09T12:19:14.145052363Z caller=frontend_scheduler_worker.go:281 level=error component=frontend msg="error contacting scheduler" err="rpc error: code = Unavailable desc = connection error: desc = \"transport: Error while dialing: dial tcp 192.168.0.2:3300: connect: connection refused\"" addr=192.168.0.2:3300
ts=2024-10-09T12:19:14.927517886Z caller=scheduler_processor.go:125 level=error component=querier-worker msg="error processing requests from scheduler" err="rpc error: code = Unavailable desc = connection error: desc = \"transport: Error while dialing: dial tcp 192.168.0.2:3300: connect: connection refused\"" addr=192.168.0.2:3300
```

**Question:**
Where is this address set (**192.168.0.2**)? I set all the fields I could find in the documentation to 127.0.0.1
