### ISSUE TITLE
Can I use consul for service discovery?

### ISSUE THREAD

**Issue by liaol** [grafana/pyroscope#3902]
I deploy pyroscope microservices without k8s.
Can I use consul for service discovery?
Can each component register to consul  and discovery others from consul on start ?
Like this:

``` yaml
ingester:
    lifecycler:
        ring:
            kvstore:
                store: consul
                prefix: collectors/
                consul:
                    host: consul:8500

distributor:
    ring:
        kvstore:
            store: consul
            prefix: collectors/
            consul:
                host: consul:8500
```

Thanks all ~
