### ISSUE TITLE
ClusterRole in helm chart has a namespace

### ISSUE THREAD

**Issue by charlesverdad** [grafana/pyroscope#3907]
#### Describe the bug

The latest helm chart version 1.12.0 fails our tests because the `ClusterRole` in the chart has a `namespace` parameter

```yaml
---
# Source: pyroscope/templates/rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: default-pyroscope-dev
  namespace: default 
  labels:
    helm.sh/chart: pyroscope-1.12.0
    app.kubernetes.io/name: pyroscope
    app.kubernetes.io/instance: pyroscope-dev
    app.kubernetes.io/version: "1.12.0"
    app.kubernetes.io/managed-by: Helm
```

#### Expected behavior

ClusterRole [should not have namespaces](https://stackoverflow.com/a/64872627), unless this is meant to be just a Role

>A Role always sets permissions within a particular [namespace](https://kubernetes.io/docs/concepts/overview/working-with-objects/namespaces); when you create a Role, you have to specify the namespace it belongs in.

>ClusterRole, by contrast, is a non-namespaced resource. The resources have different names (Role and ClusterRole) because a Kubernetes object always has to be either namespaced or not namespaced; it can't be both.

>If you want to define a role within a namespace, use a Role; if you want to define a role cluster-wide, use a ClusterRole.

https://kubernetes.io/docs/reference/access-authn-authz/rbac/
