### ISSUE TITLE
Pyroscope 1.13.0 can no longer access S3 Bucket

### ISSUE THREAD

**Issue by sberz** [grafana/pyroscope#4050]
#### Describe the bug

Since the upgrade to Pyroscope 1.13, the access to S3 fails. This causes the storage-gateway to no longer start.
We run Pyroscope on AWS EKS and use [IAM roles for service accounts](https://docs.aws.amazon.com/eks/latest/userguide/iam-roles-for-service-accounts.html) for authentication.

Likely most relevant log entries (full logs below):
```
ts=2025-03-25T16:16:29.803823714Z caller=bucket_stores.go:171 level=info msg="synchronizing Pyroscope blocks for all users"
ts=2025-03-25T16:16:29.84179215Z caller=reporter.go:201 level=debug msg="failed to read cluster seed file" err="Access Denied"
ts=2025-03-25T16:16:34.637233727Z caller=bucket_stores.go:176 level=warn msg="failed to synchronize Pyroscope blocks" err="Access Denied"
```

#### To Reproduce

1. Start Pyroscope 1.13.0 using S3 block storage 
2. Pyroscope fails to start with a generic `Access Denied` error

#### Expected behavior

Pyroscope should be able to authenticate using IRSA and access S3 block storage.

#### Environment

- Infrastructure: Kubernetes (AWS EKS)
- Deployment tool: helm 

#### Additional Context

I bisected the regression using the container images published for every commit to the main branch. 
The commit that introduced the regression is: 62c24abd9819c2473c26c918d87f0b57a7eb80ef

<details>
<summary>Storage Configuration</summary>

I use basically the same storage configuration for the latest Loki and Mimir releases where it also works as expected 

The helm release uses the following storage configuration, which did not change and worked with 1.12.0:
```yaml
        storage:
          backend: s3
          s3:
            bucket_name: <bucket-name>
            endpoint: s3.eu-central-1.amazonaws.com
```
The following variables environment variables are automatically set when using IRSA authentication:
```yaml
    - name: AWS_STS_REGIONAL_ENDPOINTS                                                                                                                                                       
      value: regional                                                                                                                                                                        
    - name: AWS_DEFAULT_REGION                                                                                                                                                               
      value: eu-central-1                                                                                                                                                                    
    - name: AWS_REGION                                                                                                                                                                       
      value: eu-central-1                                                                                                                                                                    
    - name: AWS_ROLE_ARN                                                                                                                                                                     
      value: arn:aws:iam::[redacted]:role/eks-development-v2-pyroscope                                                                                                                     
    - name: AWS_WEB_IDENTITY_TOKEN_FILE                                                                                                                                                      
      value: /var/run/secrets/eks.amazonaws.com/serviceaccount/token     
```

</details>

<details>
<summary>storage-gateway logs</summary>

```
ts=2025-03-25T16:16:24.166650518Z caller=module_service.go:72 level=debug msg="module waiting for initialization" module=usage-stats waiting_for=memberlist-kv
ts=2025-03-25T16:16:24.166664445Z caller=module_service.go:72 level=debug msg="module waiting for initialization" module=version waiting_for=memberlist-kv
ts=2025-03-25T16:16:24.166678757Z caller=module_service.go:82 level=info msg=starting module=server
ts=2025-03-25T16:16:24.16670572Z caller=module_service.go:72 level=debug msg="module waiting for initialization" module=memberlist-kv waiting_for=server
ts=2025-03-25T16:16:24.166714752Z caller=module_service.go:72 level=debug msg="module waiting for initialization" module=admin waiting_for=server
ts=2025-03-25T16:16:24.16677126Z caller=module_service.go:72 level=debug msg="module waiting for initialization" module=runtime-config waiting_for=server
ts=2025-03-25T16:16:24.166826819Z caller=module_service.go:82 level=info msg=starting module=memberlist-kv
ts=2025-03-25T16:16:24.166855752Z caller=module_service.go:82 level=info msg=starting module=runtime-config
ts=2025-03-25T16:16:24.167021524Z caller=module_service.go:72 level=debug msg="module waiting for initialization" module=version waiting_for=server
ts=2025-03-25T16:16:24.167023122Z caller=module_service.go:72 level=debug msg="module waiting for initialization" module=usage-stats waiting_for=server
ts=2025-03-25T16:16:24.167031873Z caller=module_service.go:82 level=info msg=starting module=version
ts=2025-03-25T16:16:24.16704036Z caller=module_service.go:82 level=info msg=starting module=usage-stats
ts=2025-03-25T16:16:24.167050823Z caller=module_service.go:82 level=info msg=starting module=admin
ts=2025-03-25T16:16:24.167072587Z caller=module_service.go:72 level=debug msg="module waiting for initialization" module=store-gateway waiting_for=memberlist-kv
ts=2025-03-25T16:16:24.167076902Z caller=module_service.go:72 level=debug msg="module waiting for initialization" module=store-gateway waiting_for=runtime-config
ts=2025-03-25T16:16:24.167121713Z caller=module_service.go:72 level=debug msg="module waiting for initialization" module=store-gateway waiting_for=server
ts=2025-03-25T16:16:24.167130703Z caller=module_service.go:72 level=debug msg="module waiting for initialization" module=store-gateway waiting_for=usage-stats
ts=2025-03-25T16:16:24.167219328Z caller=module_service.go:72 level=debug msg="module waiting for initialization" module=store-gateway waiting_for=version
ts=2025-03-25T16:16:24.167229119Z caller=module_service.go:82 level=info msg=starting module=store-gateway
ts=2025-03-25T16:16:24.168367179Z caller=memberlist_client.go:541 level=info msg="memberlist fast-join starting" nodes_found=18 to_join=8
ts=2025-03-25T16:16:24.168589748Z caller=log.go:245 level=debug msg="Initiating push/pull sync with:  10.102.65.161:7946"
ts=2025-03-25T16:16:24.178428086Z caller=log.go:245 level=debug msg="Initiating push/pull sync with:  10.102.89.126:7946"
ts=2025-03-25T16:16:24.185957747Z caller=log.go:245 level=debug msg="Initiating push/pull sync with:  10.102.89.127:7946"
ts=2025-03-25T16:16:24.192535556Z caller=log.go:245 level=debug msg="Initiating push/pull sync with:  10.102.94.82:7946"
ts=2025-03-25T16:16:24.199090318Z caller=log.go:245 level=debug msg="Initiating push/pull sync with:  10.102.59.206:7946"
ts=2025-03-25T16:16:24.205414888Z caller=log.go:245 level=debug msg="Initiating push/pull sync with:  10.102.79.7:7946"
ts=2025-03-25T16:16:24.212021711Z caller=log.go:245 level=debug msg="Initiating push/pull sync with:  10.102.75.33:7946"
ts=2025-03-25T16:16:24.216554719Z caller=log.go:245 level=debug msg="Failed to join 10.102.75.33:7946: EOF"
ts=2025-03-25T16:16:24.21656962Z caller=memberlist_client.go:547 level=debug msg="fast-joining node failed" node=10.102.75.33:7946 err="1 error occurred:\n\t* Failed to join 10.102.75.33:7946: EOF\n\n"
ts=2025-03-25T16:16:24.216705739Z caller=log.go:245 level=debug msg="Initiating push/pull sync with:  10.102.89.125:7946"
ts=2025-03-25T16:16:24.221151974Z caller=reporter.go:201 level=debug msg="failed to read cluster seed file" err="Access Denied"
ts=2025-03-25T16:16:24.223824303Z caller=log.go:245 level=debug msg="Initiating push/pull sync with:  10.102.77.185:7946"
ts=2025-03-25T16:16:24.232471202Z caller=memberlist_client.go:561 level=info msg="memberlist fast-join finished" joined_nodes=8 elapsed_time=65.752416ms
ts=2025-03-25T16:16:24.232510438Z caller=memberlist_client.go:573 level=info phase=startup msg="joining memberlist cluster" join_members=dns+pyroscope-memberlist.monitoring-profiles.svc.cluster.local.:7946
ts=2025-03-25T16:16:24.232584485Z caller=basic_lifecycler.go:297 level=info msg="instance not found in the ring" instance=pyroscope-store-gateway-2 ring=store-gateway
ts=2025-03-25T16:16:24.232601465Z caller=basic_lifecycler_delegates.go:63 level=info msg="not loading tokens from file, tokens file path is empty"
ts=2025-03-25T16:16:24.233118249Z caller=gateway.go:185 level=info msg="waiting until store-gateway is JOINING in the ring"
ts=2025-03-25T16:16:24.233991468Z caller=log.go:245 level=debug msg="Initiating push/pull sync with:  10.102.59.206:7946"
ts=2025-03-25T16:16:24.238144182Z caller=log.go:245 level=debug msg="Initiating push/pull sync with:  10.102.89.127:7946"
ts=2025-03-25T16:16:24.243407179Z caller=log.go:245 level=debug msg="Initiating push/pull sync with:  10.102.77.185:7946"
ts=2025-03-25T16:16:24.248291606Z caller=log.go:245 level=debug msg="Initiating push/pull sync with:  10.102.75.33:7946"
ts=2025-03-25T16:16:24.25154338Z caller=log.go:245 level=debug msg="Failed to join 10.102.75.33:7946: EOF"
ts=2025-03-25T16:16:24.251686992Z caller=log.go:245 level=debug msg="Initiating push/pull sync with:  10.102.89.126:7946"
ts=2025-03-25T16:16:24.257274547Z caller=log.go:245 level=debug msg="Initiating push/pull sync with:  10.102.89.125:7946"
ts=2025-03-25T16:16:24.262806024Z caller=log.go:245 level=debug msg="Initiating push/pull sync with:  10.102.76.5:7946"
ts=2025-03-25T16:16:24.26880542Z caller=log.go:245 level=debug msg="Initiating push/pull sync with:  10.102.60.158:7946"
ts=2025-03-25T16:16:24.273384509Z caller=log.go:245 level=debug msg="Initiating push/pull sync with:  10.102.91.68:7946"
ts=2025-03-25T16:16:24.281248288Z caller=log.go:245 level=debug msg="Initiating push/pull sync with:  10.102.65.66:7946"
ts=2025-03-25T16:16:24.287393284Z caller=log.go:245 level=debug msg="Initiating push/pull sync with:  10.102.94.82:7946"
ts=2025-03-25T16:16:24.293626044Z caller=log.go:245 level=debug msg="Initiating push/pull sync with:  10.102.60.152:7946"
ts=2025-03-25T16:16:24.293653779Z caller=log.go:245 level=debug msg="Stream connection from=10.102.60.152:37584"
ts=2025-03-25T16:16:24.295465115Z caller=log.go:245 level=debug msg="Initiating push/pull sync with:  10.102.65.161:7946"
ts=2025-03-25T16:16:24.299959596Z caller=log.go:245 level=debug msg="Initiating push/pull sync with:  10.102.89.121:7946"
ts=2025-03-25T16:16:24.305195756Z caller=log.go:245 level=debug msg="Failed to join 10.102.89.121:7946: EOF"
ts=2025-03-25T16:16:24.305325881Z caller=log.go:245 level=debug msg="Initiating push/pull sync with:  10.102.95.145:7946"
ts=2025-03-25T16:16:24.311157904Z caller=log.go:245 level=debug msg="Initiating push/pull sync with:  10.102.65.75:7946"
ts=2025-03-25T16:16:24.316936268Z caller=log.go:245 level=debug msg="Initiating push/pull sync with:  10.102.64.165:7946"
ts=2025-03-25T16:16:24.322836271Z caller=log.go:245 level=debug msg="Initiating push/pull sync with:  10.102.79.7:7946"
ts=2025-03-25T16:16:24.328079962Z caller=memberlist_client.go:580 level=info phase=startup msg="joining memberlist cluster succeeded" reached_nodes=16 elapsed_time=95.558148ms
ts=2025-03-25T16:16:26.20125844Z caller=reporter.go:201 level=debug msg="failed to read cluster seed file" err="Access Denied"
ts=2025-03-25T16:16:26.64869341Z caller=log.go:245 level=debug msg="Stream connection from=10.102.60.152:37822"
ts=2025-03-25T16:16:29.803728089Z caller=gateway.go:189 level=info msg="store-gateway is JOINING in the ring"
ts=2025-03-25T16:16:29.803823714Z caller=bucket_stores.go:171 level=info msg="synchronizing Pyroscope blocks for all users"
ts=2025-03-25T16:16:29.84179215Z caller=reporter.go:201 level=debug msg="failed to read cluster seed file" err="Access Denied"
ts=2025-03-25T16:16:34.637233727Z caller=bucket_stores.go:176 level=warn msg="failed to synchronize Pyroscope blocks" err="Access Denied"
ts=2025-03-25T16:16:34.637285654Z caller=basic_lifecycler.go:238 level=info msg="ring lifecycler is shutting down" ring=store-gateway
ts=2025-03-25T16:16:34.637444919Z caller=basic_lifecycler.go:403 level=info msg="unregistering instance from ring" ring=store-gateway
ts=2025-03-25T16:16:34.637478927Z caller=broadcast.go:48 level=debug msg="Invalidating forwarded broadcast" key=collectors/store-gateway version=5 oldVersion=4 content=[pyroscope-store-gateway-2[] oldContent=[pyroscope-store-gateway-2]
ts=2025-03-25T16:16:34.637492488Z caller=basic_lifecycler.go:278 level=info msg="instance removed from the ring" ring=store-gateway
ts=2025-03-25T16:16:34.637554504Z caller=phlare.go:630 level=error msg="module failed" module=store-gateway error="starting module store-gateway: invalid service state: Failed, expected: Running, failure: initial blocks synchronization: Access Denied"
ts=2025-03-25T16:16:34.637569978Z caller=module_service.go:133 level=debug msg="module waiting for" module=version waiting_for=store-gateway
ts=2025-03-25T16:16:34.637581847Z caller=module_service.go:110 level=debug msg=stopping module=version
ts=2025-03-25T16:16:34.637595113Z caller=module_service.go:133 level=debug msg="module waiting for" module=memberlist-kv waiting_for=store-gateway
ts=2025-03-25T16:16:34.637610419Z caller=module_service.go:133 level=debug msg="module waiting for" module=memberlist-kv waiting_for=usage-stats
ts=2025-03-25T16:16:34.63761597Z caller=module_service.go:133 level=debug msg="module waiting for" module=usage-stats waiting_for=store-gateway
ts=2025-03-25T16:16:34.637622391Z caller=module_service.go:133 level=debug msg="module waiting for" module=admin waiting_for=store-gateway
ts=2025-03-25T16:16:34.637635781Z caller=module_service.go:120 level=info msg="module stopped" module=version
ts=2025-03-25T16:16:34.637646573Z caller=module_service.go:133 level=debug msg="module waiting for" module=server waiting_for=admin
ts=2025-03-25T16:16:34.637652757Z caller=module_service.go:110 level=debug msg=stopping module=admin
ts=2025-03-25T16:16:34.637652703Z caller=module_service.go:110 level=debug msg=stopping module=usage-stats
ts=2025-03-25T16:16:34.637666688Z caller=module_service.go:133 level=debug msg="module waiting for" module=runtime-config waiting_for=store-gateway
ts=2025-03-25T16:16:34.637679678Z caller=module_service.go:110 level=debug msg=stopping module=runtime-config
ts=2025-03-25T16:16:34.637676857Z caller=module_service.go:120 level=info msg="module stopped" module=usage-stats
ts=2025-03-25T16:16:34.637685253Z caller=module_service.go:120 level=info msg="module stopped" module=admin
ts=2025-03-25T16:16:34.637705802Z caller=module_service.go:133 level=debug msg="module waiting for" module=server waiting_for=memberlist-kv
ts=2025-03-25T16:16:34.637708787Z caller=module_service.go:133 level=debug msg="module waiting for" module=memberlist-kv waiting_for=version
ts=2025-03-25T16:16:34.63771629Z caller=module_service.go:110 level=debug msg=stopping module=memberlist-kv
ts=2025-03-25T16:16:34.637727673Z caller=module_service.go:120 level=info msg="module stopped" module=runtime-config
ts=2025-03-25T16:16:34.637733628Z caller=memberlist_client.go:720 level=info msg="leaving memberlist cluster"
ts=2025-03-25T16:16:36.967658225Z caller=module_service.go:120 level=info msg="module stopped" module=memberlist-kv
ts=2025-03-25T16:16:36.967861547Z caller=module_service.go:133 level=debug msg="module waiting for" module=server waiting_for=runtime-config
ts=2025-03-25T16:16:36.967873153Z caller=module_service.go:133 level=debug msg="module waiting for" module=server waiting_for=store-gateway
ts=2025-03-25T16:16:36.967885219Z caller=module_service.go:133 level=debug msg="module waiting for" module=server waiting_for=usage-stats
ts=2025-03-25T16:16:36.967889665Z caller=module_service.go:133 level=debug msg="module waiting for" module=server waiting_for=version
ts=2025-03-25T16:16:36.967894063Z caller=module_service.go:110 level=debug msg=stopping module=server
ts=2025-03-25T16:16:36.968034614Z caller=modules.go:816 level=info msg="server stopped"
ts=2025-03-25T16:16:36.968045436Z caller=module_service.go:120 level=info msg="module stopped" module=server
ts=2025-03-25T16:16:36.968056495Z caller=phlare.go:738 level=info msg="Pyroscope stopped"
failed running pyroscope: failed services
stream closed EOF for monitoring-profiles/pyroscope-store-gateway-2 (store-gateway)
```

</details>

**Comment by airbnb-gps** [comment]
I see a similar failure. Also using environment variables and token files for IAM role authentication. This is blocking upgrade to 1.13.

**Comment by marcotuna** [comment]
Having the same problem after the upgrade to 1.13.
Like @airbnb-gps I am using `AWS_WEB_IDENTITY_TOKEN_FILE` and `AWS_ROLE_ARN` environment variables.

**Comment by simonswine** [comment]
Let me compare the difference in the thanos/objstore version. I think we need to pass an extra flag. (Loki does that https://github.com/grafana/loki/blob/4b9c8dec7ebf62c75c1dd623c81adf5516ed7d25/pkg/storage/bucket/s3/bucket_client.go#L64)

**Comment by sberz** [comment]
> Let me compare the difference in the thanos/objstore version. I think we need to pass an extra flag. (Loki does that https://github.com/grafana/loki/blob/4b9c8dec7ebf62c75c1dd623c81adf5516ed7d25/pkg/storage/bucket/s3/bucket_client.go#L64)

Using the native AWS SDK auth chain should most likely work.
For Mimir and Loki this option is disabled per default and I did not opt into it there. So I guess there are other differences.
Loki uses a relatively recent thanos/objstore version, too. The diff between the versions used by [Loki 3.4.2](https://github.com/grafana/loki/blob/v3.4.2/go.mod#L138) which works for me and [Pyroscope 1.13.0](https://github.com/grafana/pyroscope/blob/main/go.mod#L74) does not really look that suspicious: https://github.com/thanos-io/objstore/compare/a54d0f04b42a...bafad81e14fd

For reference these are my storage configs for Loki and Mimir (taken directly from the generated config maps) where I have no issues with S3

Loki:
<details>

```yaml
common:
  storage:
    s3:
      bucketnames: <bucket-name>
      region: eu-central-1
```

</details>

Mimir:
<details>

```yaml
alertmanager_storage:
  s3:
    bucket_name: <bucket-name-ruler>
blocks_storage:
  backend: s3
  s3:
    bucket_name: <bucket-name-blocks>
common:
  storage:
    backend: s3
    s3:
      endpoint: s3.eu-central-1.amazonaws.com
```

</details>
